name: "Create job dependency"

on: ['push']
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 - Step 1
        run: echo "This is Job 1, Step 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2 - Step 2
        run: echo "This is Job 2, Step 2"